// src/components/Footer.svelte
<script>
	import RawButton from "./RawButton.svelte";
</script>

<footer class="w-full flex justify-center items-center">
	<div
		class="flex justify-evenly flex-col-reverse gap-4 sm:flex-row items-center border border-neutral-300 dark:border-neutral-700 rounded-xl w-full m-2 p-2"
	>
		<div class="flex flex-col justify-center items-center">
			<h5>
				Made with love by <RawButton
					label={"Aury"}
					func={() => {
						window.location.href = "https://git.sr.ht/~aury";
					}}
				></RawButton>!
			</h5>
		</div>
		<div class="flex flex-col justify-center items-center">
			<RawButton
				label={"Home"}
				func={() => {
					window.location.href = "/";
				}}
			></RawButton>
			<RawButton
				label={"Projects"}
				func={() => {
					window.location.href = "/projects";
				}}
			></RawButton>
			<RawButton
				label={"Who we are"}
				func={() => {
					window.location.href = "/about";
				}}
			></RawButton>
			<RawButton
				label={"Github"}
				func={() => {
					window.location.href = "https://github.com/ryterm-org";
				}}
			></RawButton>
			<RawButton
				label={"Support us"}
				func={() => {
					window.location.href =
						"https://www.patreon.com/15004923/join";
				}}
			></RawButton>
		</div>
	</div>
</footer>

// app/components/footer.tsx
import { Button } from "@/components/ui/button"

export function Footer() {
    return (
        <footer className="w-full flex justify-center items-center">
            <div className="m-2 flex w-full max-w-7xl flex-col-reverse items-center justify-evenly gap-4 rounded-2xl p-4 glass sm:flex-row">
                <div className="flex flex-col items-center justify-center text-center">
                    <h5 className="text-sm text-muted-foreground">
                        Made with love by{" "}
                        <Button
                            asChild
                            variant="link"
                            className="px-1"
                        >
                            <a
                                href="https://github.com/noadevbr"
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                Noa
                            </a>
                        </Button>
                        !
                    </h5>
                </div>

                <nav className="flex flex-col items-center gap-1">
                    <Button asChild variant="ghost" size="sm">
                        <a href="/">Home</a>
                    </Button>

                    <Button asChild variant="ghost" size="sm">
                        <a href="/projects">Projects</a>
                    </Button>

                    <Button asChild variant="ghost" size="sm">
                        <a href="/about">Who we are</a>
                    </Button>

                    <Button
                        asChild
                        variant="ghost"
                        size="sm"
                    >
                        <a
                            href="https://github.com/Ryterm"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            GitHub
                        </a>
                    </Button>

                    <Button
                        asChild
                        variant="ghost"
                        size="sm"
                    >
                        <a
                            href="https://www.patreon.com/15004923/join"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            Support us
                        </a>
                    </Button>
                </nav>
            </div>
        </footer>
    )
}
